name: Radar Concursos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  rodar:
    runs-on: ubuntu-latest
    
    env:
     MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests beautifulsoup4 python-dotenv streamlit mercadopago

      - run: python app.py
